version: 2
jobs:
  build:
    docker:
      - image: cibuilds/snapcraft:stable
    working_directory: ~/klystrack-snap
    steps:
      - checkout
      - run:
          name: Build snap
          command: snapcraft
      - persist_to_workspace:
          root: .
          paths:
            - "*.snap"

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
