version: 2
jobs:
  build:
    docker:
      - image: cibuilds/snapcraft:stable
    working_directory: ~/klystrack-snap
    steps:
      - checkout
      - run:
          name: Build snap
          command: snapcraft
