version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: sudo apt-get update && apt-get install -y software-properties-common yes
      - run: sudo add-apt-repository ppa:snappy-dev/tools && apt-get update
      - run: yes | apt-get install -y snapcraft
      - checkout
      - run: snapcraft
