version: 2
jobs:
  build:
    docker:
      - image: cibuilds/snapcraft:stable
    working_directory: ~/klystrack-snap
    steps:
      - checkout
      - run:
          name: Build snap
          command: snapcraft
      - persist_to_workspace:
          root: .
          paths:
            - "*.snap"

    publish:
    docker:
      - image: cibuilds/snapcraft:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish to Store"
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push *.snap --release stable

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
              tags:
                ignore: /.*/

  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
